import { describe, expect, expectTypeOf, it } from "vitest";

import {
  BUILTIN_HOSTS,
  DISTILLY_ERROR_CODES,
  JSON_SCHEMA_DIALECT,
  WIRE_LIMITS,
  WIRE_VERSION,
  briefContractDigestSchema,
  briefMaterialRefSchema,
  captureAuditRefSchema,
  captureScopeDigestSchema,
  claimIdSchema,
  contentDigestSchema,
  conversationSourceKeySchema,
  distillyMcpTools,
  engineMethodSchemas,
  eventIdSchema,
  facetPathSchema,
  factChecksumSchema,
  hostNameSchema,
  isoDateTimeSchema,
  jobIdSchema,
  leaseIdSchema,
  materialIdSchema,
  materialSetHashSchema,
  provenanceDigestSchema,
  rawIdSchema,
  relationIdSchema,
  requestIdSchema,
  sourceGroupKeySchema,
  spaceIdSchema,
  subjectIdSchema,
  versionIdSchema,
} from "./index.js";
import type {
  CommitToolOutput,
  CoreEngineClient,
  CorrectToolOutput,
  EngineClient,
  EngineEvent,
  EngineMethodMap,
  GetToolOutput,
  IngestToolOutput,
  PendingToolOutput,
} from "./index.js";

const brandedSchemas = {
  subject: subjectIdSchema,
  space: spaceIdSchema,
  material: materialIdSchema,
  raw: rawIdSchema,
  fact: factChecksumSchema,
  content: contentDigestSchema,
  provenance: provenanceDigestSchema,
  materialSet: materialSetHashSchema,
  version: versionIdSchema,
  job: jobIdSchema,
  lease: leaseIdSchema,
  claim: claimIdSchema,
  relation: relationIdSchema,
  request: requestIdSchema,
  event: eventIdSchema,
  isoDateTime: isoDateTimeSchema,
  host: hostNameSchema,
  facet: facetPathSchema,
  sourceGroup: sourceGroupKeySchema,
  captureAudit: captureAuditRefSchema,
  captureScope: captureScopeDigestSchema,
  conversation: conversationSourceKeySchema,
  briefContract: briefContractDigestSchema,
  briefMaterial: briefMaterialRefSchema,
} as const;

describe("complete V3 protocol public contract", () => {
  it("exports the complete typed root contract", () => {
    expectTypeOf<keyof EngineMethodMap>().toEqualTypeOf<keyof typeof engineMethodSchemas>();
    expectTypeOf<EngineClient>().not.toEqualTypeOf<CoreEngineClient>();
    expectTypeOf<EngineEvent["kind"]>().toBeString();
    expectTypeOf<
      GetToolOutput | IngestToolOutput | PendingToolOutput | CommitToolOutput | CorrectToolOutput
    >().not.toBeNever();
  });

  it("pins the version, limits, ids, errors, hosts, and method registry", () => {
    expect({
      wireVersion: WIRE_VERSION,
      jsonSchemaDialect: JSON_SCHEMA_DIALECT,
      limits: WIRE_LIMITS,
      builtInHosts: BUILTIN_HOSTS,
      brandedSchemaNames: Object.keys(brandedSchemas),
      errorCodes: DISTILLY_ERROR_CODES,
      engineMethodNames: Object.keys(engineMethodSchemas),
    }).toMatchInlineSnapshot(`
      {
        "brandedSchemaNames": [
          "subject",
          "space",
          "material",
          "raw",
          "fact",
          "content",
          "provenance",
          "materialSet",
          "version",
          "job",
          "lease",
          "claim",
          "relation",
          "request",
          "event",
          "isoDateTime",
          "host",
          "facet",
          "sourceGroup",
          "captureAudit",
          "captureScope",
          "conversation",
          "briefContract",
          "briefMaterial",
        ],
        "builtInHosts": {
          "claudeCode": "claude-code",
          "codex": "codex",
        },
        "engineMethodNames": [
          "subjects.create",
          "subjects.list",
          "subjects.resolve",
          "subjects.archive",
          "subjects.purge",
          "materials.ingest",
          "materials.ingestFiles",
          "materials.list",
          "materials.get",
          "distill.pending",
          "distill.brief",
          "distill.renew",
          "distill.release",
          "distill.commit",
          "distill.redistill",
          "profiles.get",
          "profiles.prompt",
          "profiles.status",
          "profiles.correct",
          "versions.list",
          "versions.diff",
          "versions.promote",
          "versions.reject",
          "versions.rollback",
          "versions.lineage",
          "hosts.install",
          "hosts.uninstall",
          "hosts.export",
          "library.list",
          "library.rebuild",
          "reviews.list",
          "bundles.inspect",
          "bundles.import",
          "bundles.export",
          "system.doctor",
        ],
        "errorCodes": [
          "invalid_input",
          "not_found",
          "already_exists",
          "ambiguous_subject",
          "idempotency_conflict",
          "nothing_pending",
          "lease_conflict",
          "lease_expired",
          "stale_job",
          "briefing_too_large",
          "evidence_invalid",
          "context_too_large",
          "review_conflict",
          "busy",
          "storage_corrupt",
          "schema_unsupported",
          "index_unavailable",
          "host_unsupported",
          "adapter_failed",
          "permission_denied",
        ],
        "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
        "limits": {
          "claimTextBytes": 16384,
          "correctionTextBytes": 65536,
          "evidencePerOperation": 64,
          "ingestMaterials": 32,
          "labelBytes": 1024,
          "listLimit": 200,
          "materialContentBytes": 1048576,
          "openRecordEntries": 64,
          "patchOperations": 256,
          "queryBytes": 4096,
          "quoteBytes": 65536,
          "reasonBytes": 8192,
          "smallArrayItems": 64,
          "toolInputBytes": 4194304,
          "uriBytes": 8192,
        },
        "wireVersion": "3",
      }
    `);
  });

  it("snapshots every serializable field of the five MCP descriptors", () => {
    expect(
      distillyMcpTools.map((tool) =>
        Object.fromEntries(
          Object.entries(tool).filter(([key]) => key !== "input" && key !== "output"),
        ),
      ),
    ).toMatchSnapshot();
  });
});
